source 'https://rubygems.org'

gem 'jekyll', '~> 4.2.0'
gem 'webrick', '~> 1.7'

group :jekyll_plugins do
  gem 'jekyll-archives', '~> 2.2.1'
  gem 'jekyll-seo-tag', '~> 2.7.1'
  gem 'jekyll-sitemap', '~> 1.4.0'
end
